# Site settings
title: Dan Bennett
tagline: The Brain Dump
email: dan@dan-bennett.me
description: > # this means to ignore newlines until "baseurl:"
  The Brain Dump
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dan-bennett.me" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Dan Bennett"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
encoding: utf-8
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#2D7EAD" #"#eb9719"
  # Social media links, leave blank to ignore
  social:
    github: DanBennettUK
    twitter: DanBennett
    facebook: DanBennettOfficial
    gplus: +danbennettuk
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-36326232-1
  google_webmaster_key:

# Build settings
markdown: kramdown
#markdown: CommonMark

# Permalinks
#permalink: pretty 
permalink: /:title

# Pagination config
paginate: 5
gems: [jekyll-paginate]

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
